name: sehety
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_sign_in: '^4.5.1'
  image_picker: ^0.8.4+2
  file_picker: ^4.4.0
  firebase_storage:
  multi_select_flutter: ^4.0.0
  multiselect_formfield: ^0.1.0
  intl: ^0.17.0
  flutter_pdfview: ^1.3.1
  syncfusion_flutter_pdfviewer: ^20.4.54
  flutter_local_notifications: ^12.0.4
  flutter_datetime_picker: ^1.5.1
  awesome_notifications: ^0.7.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  provider: ^6.0.2

flutter:
  fonts:
    - family: Josefin_Sans
      fonts:
        - asset: fonts/Josefin_Sans/JosefinSans-Bold.ttf
        - asset: fonts/Josefin_Sans/JosefinSans-BoldItalic.ttf
        - asset: fonts/Josefin_Sans/JosefinSans-ExtraLight.ttf
        - asset: fonts/Josefin_Sans/JosefinSans-Medium.ttf
        - asset: fonts/Josefin_Sans/JosefinSans-MediumItalic.ttf
        - asset: fonts/Josefin_Sans/JosefinSans-Regular.ttf
        - asset: fonts/Josefin_Sans/JosefinSans-SemiBold.ttf

  uses-material-design: true
  assets:
    - images/
